// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT.
//
// (unless you know what you're doing.)
//
// This file is maintained by the IncrementBuildNumber tool.
// MAJOR_VERSION, MINOR_VERSION and REVISION_STRING may be manually modified.
// LAST_BUILD_NUMBER and REVISION_NUMBER are the only bits controlled by the tool.
//
// Last update time: Wed Aug 12 20:37:49 2015
//
// These are used to generate game defines.
// :KEY MAJOR_VERSION 		0
// :KEY MINOR_VERSION 		1
// :KEY LAST_BUILD_NUMBER 		1022
// :KEY REVISION_NUMBER 		0
// :KEY REVISION_STRING 		


#ifndef _VERSION_INFO_H_
#define _VERSION_INFO_H_
#pragma once


// These are generated from the values above. DO NOT MANUALLY EDIT.
#define GAME_VERSION 		"0.1 (Build 1021)"
#define FILEVER 		0,1,1021,0
#define PRODUCTVER 		0,1,1021,0
#define STRFILEVER 		"0, 1, 1021, 0\0"
#define STRPRODUCTVER 		"0, 1, 1021, 0\0"


#endif //_VERSION_INFO_H_
